In [15]:
import pandas as pd
import numpy as np
from sklearn.metrics import pairwise_distances

In [16]:
data_user = pd.read_csv(r'C:\Users\sneha\anaconda assignment\excel\u .data',delimiter = "\t", header = None)

In [17]:
data_user

         0     1  2          3
0      196   242  3  881250949
1      186   302  3  891717742
2       22   377  1  878887116
3      244    51  2  880606923
4      166   346  1  886397596
...    ...   ... ..        ...
99995  880   476  3  880175444
99996  716   204  5  879795543
99997  276  1090  1  874795795
99998   13   225  2  882399156
99999   12   203  3  879959583

[100000 rows x 4 columns]

In [18]:
data_user.columns = ["userid", "movieid", "rating", "timestamp"]

In [19]:
data_user['timestamp'] = pd.to_datetime(data_user['timestamp'], unit = 's')

In [20]:
data_user

       userid  movieid  rating           timestamp
0         196      242       3 1997-12-04 15:55:49
1         186      302       3 1998-04-04 19:22:22
2          22      377       1 1997-11-07 07:18:36
3         244       51       2 1997-11-27 05:02:03
4         166      346       1 1998-02-02 05:33:16
...       ...      ...     ...                 ...
99995     880      476       3 1997-11-22 05:10:44
99996     716      204       5 1997-11-17 19:39:03
99997     276     1090       1 1997-09-20 22:49:55
99998      13      225       2 1997-12-17 22:52:36
99999      12      203       3 1997-11-19 17:13:03

[100000 rows x 4 columns]

In [21]:
user_item_data = data_user.pivot(index='userid', columns='movieid', values='rating').fillna(0)

In [22]:
pairwise_distances(user_item_data, metric='euclidean')

array([[ 0.        , 65.2533524 , 65.91661399, ..., 63.17436189,
        67.74215822, 61.8950725 ],
       [65.2533524 ,  0.        , 35.62302626, ..., 33.24154028,
        44.71017781, 53.24471805],
       [65.91661399, 35.62302626,  0.        , ..., 28.10693865,
        41.88078318, 51.6139516 ],
       ...,
       [63.17436189, 33.24154028, 28.10693865, ...,  0.        ,
        41.32795664, 49.2138192 ],
       [67.74215822, 44.71017781, 41.88078318, ..., 41.32795664,
         0.        , 55.13619501],
       [61.8950725 , 53.24471805, 51.6139516 , ..., 49.2138192 ,
        55.13619501,  0.        ]], shape=(943, 943))

In [23]:
user_user_similiraty = pd.DataFrame(pairwise_distances(user_item_data, metric='euclidean'), columns = user_list, index= user_list)

In [24]:
user_user_similiraty

,1,2,3,4,5,6,7,8,9,10,...,934,935,936,937,938,939,940,941,942,943
1,0.000000,65.253352,65.916614,65.360539,61.147363,63.348244,78.689262,60.695964,64.776539,67.527772,...,64.591021,65.030762,67.111847,62.841069,66.279710,66.775744,62.369865,63.174362,67.742158,61.895073
2,65.253352,0.000000,35.623026,33.970576,50.009999,55.812185,84.699469,40.816663,33.734256,60.646517,...,54.626001,32.848135,45.166359,29.137605,39.153544,37.828561,42.355637,33.241540,44.710178,53.244718
3,65.916614,35.623026,0.000000,25.238859,47.222876,57.775427,83.958323,36.428011,29.410882,60.423505,...,54.543561,32.893768,47.822589,30.724583,40.224371,37.443290,40.236799,28.106939,41.880783,51.613952
4,65.360539,33.970576,25.238859,0.000000,46.701178,57.645468,83.282651,34.058773,28.284271,60.299254,...,53.870214,32.542280,48.249352,28.160256,39.484174,36.972963,39.242834,26.814175,40.853396,50.685304
5,61.147363,50.009999,47.222876,46.701178,0.000000,60.728906,77.272246,45.464272,45.727453,64.117080,...,53.637673,47.201695,59.371710,46.151923,51.322510,50.219518,49.040799,43.794977,52.516664,52.383203
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
939,66.775744,37.828561,37.443290,36.972963,50.219518,59.799666,84.787971,41.194660,36.152455,63.269266,...,57.262553,30.066593,48.301139,33.704599,35.972211,0.000000,46.097722,33.166248,48.145612,52.345009
940,62.369865,42.355637,40.236799,39.242834,49.040799,54.415071,78.447435,42.000000,40.298883,56.868269,...,52.000000,42.626283,53.553711,39.937451,47.254629,46.097722,0.000000,39.433488,46.054316,52.545219
941,63.174362,33.241540,28.106939,26.814175,43.794977,55.533774,83.528438,33.808283,26.134269,59.101607,...,53.207142,28.425341,44.553339,26.153394,35.411862,33.166248,39.433488,0.000000,41.327957,49.213819
942,67.742158,44.710178,41.880783,40.853396,52.516664,56.178288,80.529498,44.821870,41.916584,62.120850,...,56.115951,44.384682,57.349804,42.071368,50.239427,48.145612,46.054316,41.327957,0.000000,55.136195
943,61.895073,53.244718,51.613952,50.685304,52.383203,61.692787,77.129761,47.885280,49.929951,65.825527,...,59.253692,48.476799,61.000000,50.655701,53.347915,52.345009,52.545219,49.213819,55.136195,0.000000

In [25]:
user_user_similiraty = user_user_similiraty.sort_values(ascending= True, by=1)

In [26]:
user_user_similiraty.iloc[1:,0].head(5)

738    55.063600
521    55.235858
933    55.614746
715    57.070132
44     57.402091
Name: 1, dtype: float64

In [27]:
user_list = list(set(data_user.userid))

In [28]:
movies_list = list(set(data_user.movieid))

In [29]:
user_1 = set(data_user.loc[data_user['userid'] == 1,'movieid'])

In [30]:
user_738 = set(data_user.loc[data_user['userid'] == 738,'movieid'])

In [31]:
reco = user_738.difference(user_1)

In [32]:
data_movies = pd.read_csv(r'C:\Users\sneha\anaconda assignment\excel\u .item',delimiter = '\|', header = None, encoding="ISO-8859-1")

C:\Users\sneha\AppData\Local\Temp\ipykernel_21308\3513001335.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  data_movies = pd.read_csv(r'C:\Users\sneha\anaconda assignment\excel\u .item',delimiter = '\|', header = None, encoding="ISO-8859-1")

In [33]:
data_movies = data_movies.iloc[:,:2]

In [34]:
data_movies.columns = ['movieid','movie_name']

In [35]:
data_movies

      movieid                                 movie_name
0           1                           Toy Story (1995)
1           2                           GoldenEye (1995)
2           3                          Four Rooms (1995)
3           4                          Get Shorty (1995)
4           5                             Copycat (1995)
...       ...                                        ...
1677     1678                          Mat' i syn (1997)
1678     1679                           B. Monkey (1998)
1679     1680                       Sliding Doors (1998)
1680     1681                        You So Crazy (1994)
1681     1682  Scream of Stone (Schrei aus Stein) (1991)

[1682 rows x 2 columns]

In [36]:
list(reco)[0:5]

[385, 517, 393, 650, 651]

In [37]:
data_movies.loc[data_movies['movieid'].isin(list(reco)[0:5]),['movie_name']]

                                          movie_name
384                                 True Lies (1994)
392                            Mrs. Doubtfire (1993)
516                                 Manhattan (1979)
649  Seventh Seal, The (Sjunde inseglet, Det) (1957)
650                                     Glory (1989)

In [32]:
item_user_data = data_user.pivot(index='movieid', columns='userid', values='rating').fillna(0)

In [33]:
pairwise_distances(item_user_data, metric='euclidean')

array([[ 0.        , 77.72387021, 80.07496488, ..., 84.79976415,
        84.68766144, 84.68766144],
       [77.72387021,  0.        , 42.17819342, ..., 38.36665219,
        38.19685851, 38.19685851],
       [80.07496488, 42.17819342,  0.        , ..., 31.0322413 ,
        31.11269837, 30.82207001],
       ...,
       [84.79976415, 38.36665219, 31.0322413 , ...,  0.        ,
         3.60555128,  3.60555128],
       [84.68766144, 38.19685851, 31.11269837, ...,  3.60555128,
         0.        ,  4.24264069],
       [84.68766144, 38.19685851, 30.82207001, ...,  3.60555128,
         4.24264069,  0.        ]], shape=(1682, 1682))

In [34]:
movie_movie_similarity = pd.DataFrame(pairwise_distances(item_user_data, metric='euclidean'), columns = movies_list , index= movies_list)

In [35]:
movie_movie_similarity = movie_movie_similarity.sort_values(ascending= True, by=1)

In [36]:
movie_movie_similarity.iloc[1:,0].head(5)

121    63.529521
405    65.764732
117    65.840717
151    66.835619
118    67.535176
Name: 1, dtype: float64

In [37]:
movie_1 = set(data_user.loc[data_user['movieid'] == 1,'userid'])

In [38]:
movie_121 = set(data_user.loc[data_user['movieid'] == 121,'userid'])

In [39]:
roc2 = (movie_121.difference(movie_1))

In [40]:
data_user.loc[data_user['userid'].isin(list(roc2)[0:5]),['userid']]

       userid
2          22
39          7
88         11
139         7
187         7
...       ...
98173       7
98452      14
98485      22
98732       7
98734      22

[832 rows x 1 columns]

In [41]:
for i in [1,5,10]:
  movie_list = movie_movie_similarity[i].sort_values()[1:6].index
  print('top 5 movies for movie',i)
  print(data_movies.loc[data_movies['movieid'].isin(movie_list),['movie_name']])
  print('-------------------------')

top 5 movies for movie 1
                                       movie_name
116                              Rock, The (1996)
117                                Twister (1996)
120                 Independence Day (ID4) (1996)
150  Willy Wonka and the Chocolate Factory (1971)
404                    Mission: Impossible (1996)
-------------------------
top 5 movies for movie 5
                                  movie_name
550                 Lord of Illusions (1995)
768                             Congo (1995)
778                         Drop Zone (1994)
815   Candyman: Farewell to the Flesh (1995)
1470                         Hideaway (1995)
-------------------------
top 5 movies for movie 10
                         movie_name
129              Kansas City (1996)
717   In the Bleak Midwinter (1995)
969             Hear My Song (1991)
1055                  Cronos (1992)
1114           Twelfth Night (1996)
-------------------------

In [42]:
for i in [1,5,10]:
  user_list = user_user_similiraty.iloc[1:,i].sort_values(ascending= True).iloc[0:5].index
  print('top 5 user for user',i)
  print(data_user.loc[data_user['userid'].isin(user_list),['userid']].drop_duplicates())
  print('---------------')

top 5 user for user 1
       userid
549       131
700         2
2005      266
43998     701
67397     926
---------------
top 5 user for user 5
       userid
9           6
295       123
1939      321
29789     553
65993     929
---------------
top 5 user for user 10
       userid
88         11
325       187
696       208
3732      163
32166     575
---------------

In [55]:
for i in [10,20,30,50,100]:
    print('Recommended Movies for user ',i)
    top_1_similar_user = user_user_similiraty[i].sort_values()[1:2].index
    print('Top 1 Similar users for user ',i, 'are: ', top_1_similar_user)
    for j in range(0,len(top_1_similar_user)):
        u1st = i
        u2nd = top_1_similar_user[j]
        print('Movie to recommend to user ',u1st, 'on the basis on user ',u2nd)
        sm_1stu = set(data_user[data_user['userid']==u1st]['movieid'].values)
        sm_2ndu = set(data_user[data_user['userid']==u2nd]['movieid'].values)
        movie_list = list(sm_2ndu - sm_1stu)
        print(movie_list)
        print(data_movies[data_movies['movieid'].isin(movie_list)]['movie_name'])
    print("---------------------")

Recommended Movies for user  10
Top 1 Similar users for user  10 are:  Index([321], dtype='int64')
Movie to recommend to user  10 on the basis on user  321
[np.int64(514), np.int64(515), np.int64(1028), np.int64(131), np.int64(647), np.int64(8), np.int64(523), np.int64(14), np.int64(526), np.int64(143), np.int64(19), np.int64(20), np.int64(659), np.int64(1050), np.int64(30), np.int64(287), np.int64(419), np.int64(1194), np.int64(428), np.int64(45), np.int64(173), np.int64(942), np.int64(1331), np.int64(52), np.int64(61), np.int64(190), np.int64(193), np.int64(1101), np.int64(207), np.int64(83), np.int64(212), np.int64(213), np.int64(86), np.int64(87), np.int64(215), np.int64(89), np.int64(730), np.int64(855), np.int64(607), np.int64(224), np.int64(736), np.int64(863), np.int64(485), np.int64(614), np.int64(1126), np.int64(491), np.int64(494), np.int64(631), np.int64(633), np.int64(507), np.int64(382)]
7                                             Babe (1995)
13                                     Postino, Il (1994)
18                                  Antonia's Line (1995)
19                              Angels and Insects (1995)
29                                   Belle de jour (1967)
44                             Eat Drink Man Woman (1994)
51                     Madness of King George, The (1994)
60                             Three Colors: White (1994)
82                          Much Ado About Nothing (1993)
85                         Remains of the Day, The (1993)
86                     Searching for Bobby Fischer (1993)
88                                    Blade Runner (1982)
130                         Breakfast at Tiffany's (1961)
142                            Sound of Music, The (1965)
172                            Princess Bride, The (1987)
189                                        Henry V (1989)
192                               Right Stuff, The (1983)
206                             Cyrano de Bergerac (1990)
211             Unbearable Lightness of Being, The (1988)
212                            Room with a View, A (1986)
214                                Field of Dreams (1989)
223                                       Ridicule (1996)
286                                  Marvin's Room (1996)
381     Adventures of Priscilla, Queen of the Desert, ...
418                                   Mary Poppins (1964)
427                               Harold and Maude (1971)
484                                   My Fair Lady (1964)
490                  Adventures of Robin Hood, The (1938)
493                                His Girl Friday (1940)
506                      Streetcar Named Desire, A (1951)
513                                     Annie Hall (1977)
514                                      Boot, Das (1981)
522                                 Cool Hand Luke (1967)
525                                        Ben-Hur (1959)
606                                        Rebecca (1940)
613                                          Giant (1956)
630                               Crying Game, The (1992)
632                             Christmas Carol, A (1938)
646                                            Ran (1985)
658                           Arsenic and Old Lace (1944)
729                Queen Margot (Reine Margot, La) (1994)
735                                    Shadowlands (1993)
854                                           Diva (1981)
862     Garden of Finzi-Contini, The (Giardino dei Fin...
941                  What's Love Got to Do with It (1993)
1027                              Grumpier Old Men (1995)
1049                      Ghost and Mrs. Muir, The (1947)
1100                     Six Degrees of Separation (1993)
1125                      Old Man and the Sea, The (1958)
1193                            Once Were Warriors (1994)
1330    Last Klezmer: Leopold Kozlowski, His Life and ...
Name: movie_name, dtype: str
---------------------
Recommended Movies for user  20
Top 1 Similar users for user  20 are:  Index([55], dtype='int64')
Movie to recommend to user  20 on the basis on user  55
[np.int64(257), np.int64(1089), np.int64(7), np.int64(685), np.int64(79), np.int64(273), np.int64(117), np.int64(254), np.int64(56), np.int64(89), np.int64(1016)]
6                Twelve Monkeys (1995)
55                 Pulp Fiction (1994)
78                Fugitive, The (1993)
88                 Blade Runner (1982)
116                   Rock, The (1996)
253              Batman & Robin (1997)
256                Men in Black (1997)
272                        Heat (1995)
684          Executive Decision (1996)
1015                    Con Air (1997)
1088    Speed 2: Cruise Control (1997)
Name: movie_name, dtype: str
---------------------
Recommended Movies for user  30
Top 1 Similar users for user  30 are:  Index([461], dtype='int64')
Movie to recommend to user  30 on the basis on user  461
[np.int64(327), np.int64(9), np.int64(682), np.int64(748), np.int64(269), np.int64(302), np.int64(1006), np.int64(305), np.int64(121), np.int64(347), np.int64(285), np.int64(158), np.int64(575)]
8                                 Dead Man Walking (1995)
120                         Independence Day (ID4) (1996)
157                            Weekend at Bernie's (1989)
268                                Full Monty, The (1997)
284                                 Secrets & Lies (1996)
301                              L.A. Confidential (1997)
304                                 Ice Storm, The (1997)
326                                       Cop Land (1997)
346                                    Wag the Dog (1997)
574     City Slickers II: The Legend of Curly's Gold (...
681                I Know What You Did Last Summer (1997)
747                                     Saint, The (1997)
1005    Until the End of the World (Bis ans Ende der W...
Name: movie_name, dtype: str
---------------------
Recommended Movies for user  50
Top 1 Similar users for user  50 are:  Index([685], dtype='int64')
Movie to recommend to user  50 on the basis on user  685
[np.int64(289), np.int64(872), np.int64(873), np.int64(299), np.int64(875), np.int64(333), np.int64(269), np.int64(302), np.int64(334), np.int64(337), np.int64(882), np.int64(340), np.int64(886), np.int64(991)]
268          Full Monty, The (1997)
288                    Evita (1996)
298                  Hoodlum (1997)
301        L.A. Confidential (1997)
332                Game, The (1997)
333                   U Turn (1997)
336        House of Yes, The (1997)
339            Boogie Nights (1997)
871               Love Jones (1997)
872          Picture Perfect (1997)
874          She's So Lovely (1997)
881        Washington Square (1997)
885    Life Less Ordinary, A (1997)
990            Keys to Tulsa (1997)
Name: movie_name, dtype: str
---------------------
Recommended Movies for user  100
Top 1 Similar users for user  100 are:  Index([856], dtype='int64')
Movie to recommend to user  100 on the basis on user  856
[np.int64(322), np.int64(327), np.int64(748), np.int64(749), np.int64(688), np.int64(307), np.int64(312)]
306                      Devil's Advocate, The (1997)
311    Midnight in the Garden of Good and Evil (1997)
321                             Murder at 1600 (1997)
326                                   Cop Land (1997)
687                         Leave It to Beaver (1997)
747                                 Saint, The (1997)
748                            MatchMaker, The (1997)
Name: movie_name, dtype: str
---------------------